---
- name: Arista Set Banner
  hosts: arista
  gather_facts: no

  tasks: 
  - name: Run Show Command 
    arista.eos.eos_banner:
      banner: login
      text: |
        Warning! This system is restricted solely by Ellis Coperation. This is a Production Network System. This system is being monitored for all malicious activity. Created by AAP 
      state: present  
