---
- name: Backup Arista EOS Device Configurations
  hosts: arista
  gather_facts: yes
  vars:
    backup_path: "/path/to/backup/directory" # Define your backup location

  tasks:
    - name: Backup current running configuration
      arista.eos.eos_config:
        backup: yes
        backup_options:
          dir_path: /tmp/ 
          filename: "{{ inventory_hostname }}.txt"
      register: config_output

    - name: Copy file to destination server
      ansible.builtin.copy:
        src: "{{ config_output.backup_path }}"
        dest: "/home/ec2-user/network_backups/arista/{{ inventory_hostname }}/{{ '%Y-%m-%d %H:%M:%S' | strftime }}_running-config.bak"
        mode: "0644"
        become: true
      delegate_to: backup-server