---
- name: Backup Arista EOS Device Configurations
  hosts: arista
  gather_facts: yes
  vars:
    backup_path: "/path/to/backup/directory" # Define your backup location

  tasks:
    - name: Backup current running configuration
      arista.eos.eos_config:
        backup: yes
        backup_options:
      register: backup_result
    
    - name: Display backup
      debug:
        var: backup_result

    - name: Copy file to destination server
      ansible.builtin.copy:
        src: "{{ backup_result.stdout }}"
        dest: "/home/ec2-user/network_backups/arista/{{ inventory_hostname }}/{{ '%Y-%m-%d %H:%M:%S' | strftime }}_running-config.bak"
        mode: "0644"
        remote_src: yes
      delegate_to: localhost
