---
- name: Arista Set Banner
  hosts: arista
  gather_facts: no

  tasks: 
  - name: Set Banner for Arista Router
    arista.eos.eos_banner:
      banner: login
      text: |
        Warning! This system is restricted solely by Ellis Corp. This is a Production Network System. This system is being monitored for all malicious activity! Created by AAP 
      state: present  
