---
- name: Arista Create Users
  hosts: arista
  gather_facts: no

  tasks: 
  - name: Arista Create Network Ops Admin User
    arista.eos.eos_user:
      name: netadmin
      configured_password: "{{ net_password }}"
      update_password: always
      privilege: 15
      state: present
 
