---
- name: Arista Create Users
  hosts: arista
  gather_facts: no

  tasks: 
  - name: Run Show Command 
    arista.eos.eos_user:
      name: netadmin
      configured_password: "{{ net_password }}"
      update_password: always
      privilege: 10
      state: present
 
