---
- name: Arista Show Router Commands
  hosts: arista
  gather_facts: no

  tasks: 
  - name: Run Show Command 
    arista.eos.eos_command:
      commands: "{{ command }}"
    register: output

  - name: Display Command Output  
    debug:
      msg: "{{ output.stdout_lines }}"    