---
- name: Arista Set Banner
  hosts: arista
  gather_facts: no

  tasks: 
  - name: Run Show Command 
    arista.eos.eos_banner:
      banner: login
      text: |
        This is a Production Network System. This system is being monitored for any malicious activity.
        Created by AAP 
      state: present  
