---
- name: Arista Set Hostname
  hosts: arista
  gather_facts: no

  tasks: 
  - name: Set Router Hostname
    arista.eos.eos_hostname:
      config:
        hostname: arista_rtr1
      state: merged 
