---
- name: Arista Configure Vlans
  hosts: arista
  gather_facts: no

  tasks: 
  - name: Remove VLANS
    arista.eos.eos_vlans:
      config:
        - vlan_id: 10
          name: test
        - vlan_id: 20
          name: dev
        - vlan_id: 30
          name: quarantine 
        - vlan_id: 40
          name: production
      state: deleted
