---
- name: snmp ro/rw string configuration
  hosts: cisco
  gather_facts: no

  tasks: 
  - name: Ensure that the desired snmp strings are present
    cisco.ios.config:
      commands:
        - snmp-server community ansible-public-git RO
        - snmp-server community ansible-private-git RW
