---
- name: Generate Web Report
  hosts: webservers
  gather_facts: no
  become: true

  tasks:
  - name: Creating reporting
    copy:
      src: /var/lib/awx/projects/playbooks/cisco_facts.html
      dest: /var/www/html/index.html
      owner: apache
      mode: "664"

  - name: Restart Apache
    service:
      name: httpd
      state: restarted
