---
- name: create netops user
  hosts: cisco
  gather_facts: false

  tasks:
  - name: Create Network Operator User        
    cisco.ios.ios_user:
      name: "{{ name }}"
      configured_password: "{{ password }}"
      privilege: 15
      state: present
